### ISSUE TITLE
Nova editor functions disabled by advanced PHP

### ISSUE THREAD

**Issue by motownphilippe** [dennisosaj/advancedphp.novaextension#1]
I like advanced PHP a lot, but it stops some of Nova's editor functions. 
For eg:

- code structure map (symbols) is empty when syntax is set to advanced PHP
- function blocks are not recognised by Nova so that I cannot 'Fold Methods and Functions' when syntax is set to advanced PHP
- double clicking a variable does not select the '$' even when 'Select prefixes when double clicking variables' is enabled in Nova's preferences. 

I love what you have going with Advanced PHP, I would love it even more if these issues were fixed. Thanks!

**Comment by dennisosaj** [comment]
Thanks for your feedback. Symbolication is in progress and will be released with the next version. Double click with var prefix is on my list. Thanks!

**Comment by dennisosaj** [comment]
Hey ho, the issues should be fixed with the new release of "advanced PHP", which I just uploaded a few seconds ago. You can download the update through the Extension Library, if you should have disabled auto updates. Check the Changelog for more.
