### ISSUE TITLE
Added support for Advanced PHP

### ISSUE THREAD

**Issue by TeriyakiBomb** [dennisosaj/advancedphp.novaextension#10]
Hello there! I maintain a theme for Nova and I just added support for Advanced PHP :)

https://extensions.panic.com/extensions/teriyaki/teriyaki.Ashokai/

**Comment by dennisosaj** [comment]
Hi, thanks for adding it to your theme. Will add a note to the Readme on the next change.

**Comment by TeriyakiBomb** [comment]
Awesome :) I've attached the logo in case you want to use it 

![ashokai-logo](https://github.com/dennisosaj/advancedphp.novaextension/assets/12913978/47323545-6f92-4ea2-8d31-0347de8396ae)
