### ISSUE TITLE
Breaks compatibility with PHP CS Fixer

### ISSUE THREAD

**Issue by BenBornschein** [dennisosaj/advancedphp.novaextension#2]
Hello,
when advanced PHP (great extension by the way, thank you!) is active, the extension PHP CS Fixer doesn't work anymore.

Using PHP CS Fixer version 1.0.3 and advanced PHP version 1.1.0

**Comment by dennisosaj** [comment]
Hello Ben,
I just tested PHP CS Fixer together with advanced PHP and it worked. I have to say that I just downloaded PHP CS Fixer and didn't made any preference changes.

**Comment by BenBornschein** [comment]
I can confirm the issue is gone/not replicable. I had to restart Nova a couple times, this IDE is still bugged...Sorry!
