### ISSUE TITLE
? Nova 4 compatibility. 

### ISSUE THREAD

**Issue by motownphilippe** [dennisosaj/advancedphp.novaextension#3]
Loving advanced PHP in Nova.
I think it may have broken with version 4 of Nova.

**Comment by dennisosaj** [comment]
Heyho, thanks again <3
I will look into it and let you know.

**Comment by dennisosaj** [comment]
New Update is available. For proper highlighting please download the new VariaTheme, too.

**Comment by motownphilippe** [comment]
Working beautifully!
