### ISSUE TITLE
New Selectors: USE statements and SEMICOLON

### ISSUE THREAD

**Issue by keisto** [dennisosaj/advancedphp.novaextension#4]
Hello there,

I was wondering if you could add selectors for these `use` statements. In **sublime text** they appear like: 

<img width="742" alt="Screen Shot 2021-02-19 at 10 40 12 AM" src="https://user-images.githubusercontent.com/2490903/108547265-1d304000-729f-11eb-9c91-65a2a99b1fbd.png">
_(SUBLIME TEXT SCREENSHOT ABOVE)_

---

and right now in **advanced-php** it looks like :

<img width="694" alt="Screen Shot 2021-02-19 at 10 40 27 AM" src="https://user-images.githubusercontent.com/2490903/108547349-3638f100-729f-11eb-850c-3ca594c2a4d6.png">
_(NOVA SCREENSHOT ABOVE)_

---

I'm not sure if that's easy target text after the last `\` or if its the only text:

<img width="236" alt="Screen Shot 2021-02-19 at 10 49 08 AM" src="https://user-images.githubusercontent.com/2490903/108548012-1a821a80-72a0-11eb-97c2-de65e1cbffc0.png">
_(SUBLIME TEXT SCREENSHOT ABOVE)_

---

Nova also has a `javascript.semicolon` selector and I'd like that to be in php too. Right now it falls under `advphp.operator`.

**Comment by dennisosaj** [comment]
Thanks for bringing that to my attention. I will look into it.

**Comment by dennisosaj** [comment]
The "use" keyword is added and namespace highlighting is integrated. Unfortunately I can't grab the last word, just every single one. The best I can do atm, will look into it for future updates:

<img width="262" alt="Screenshot 2021-03-06 at 13 04 10" src="https://user-images.githubusercontent.com/48364940/110206425-cd946b80-7e7d-11eb-8806-5d6207769857.png">

**Comment by dennisosaj** [comment]
Oh forgot to mention, that you have an own semicolon selector for advphp now, too. Just style "advphp.semicolon".
