### ISSUE TITLE
`static` keyword not targeted for highlighting

### ISSUE THREAD

**Issue by blakewatson** [dennisosaj/advancedphp.novaextension#5]
```php
<?php

class Foo {
  static function bar() {}
}
```

It looks like the keyword, `static`, isn’t being targeted for highlighting.

For example, I would have expected `static` to be pink/purple here:

<img width="574" alt="Screen Shot 2021-03-05 at 5 11 15 PM" src="https://user-images.githubusercontent.com/801425/110184175-eb0dfa80-7dd5-11eb-8f2c-d81a27af041d.png">

**Comment by dennisosaj** [comment]
Keyword is added.
