### ISSUE TITLE
File scrolls to top on save

### ISSUE THREAD

**Issue by MarcPinnell** [dennisosaj/advancedphp.novaextension#8]
After editing a file and then saving, file scrolls back to the first line. Verified by turning off 'advanced PHP'. Behavior goes away.

**Comment by dennisosaj** [comment]
Can't reproduce this issue. Which Version of Nova are you using. Please try to disable all extension and test it again just with advancedPHP.

**Comment by MarcPinnell** [comment]
Nova 6.2 build 271290
Wouldn't you know it. After being annoyed by it for days, it seems to have stopped. I cannot reproduce this morning! I'll check back in a day or so with an update if it comes back.

**Comment by MarcPinnell** [comment]
Ok, figured it out. It is a problem with PHP CS Fixer Extension. I move this discussion over to them! Sorry for the false alarm.
